name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
defaults:
  run:
    shell: nu {0}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - uses: hustcer/setup-nu@main
        with:
          check-latest: true
          features: mcp

      - name: install
        run: bun install --frozen-lockfile

      - name: check
        run: bun run mcp:check

      - name: build
        run: bun run mcp:build
