name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Install Nushell
        run: |
          source /home/runner/.bash_profile
          cargo install nu

      - name: Run tests
        run: bun --cwd=server test

      - name: Build
        run: bun run mcp:build
